/************************************************************
CRUMB
************************************************************/

:root {
  --crumb-link-color: var(--navy);
  --crumb-active-color: var(--default-color);
  --crumb-trail-color: var(--grey-l3);
  --crumb-trail-gap: 1rem;
}

.#{$prefix}crumb {
  display: inline-flex;
  flex: 1;
  align-items: center;
  &\/item {
    color: var(--crumb-link-color);
    &.is-active {
      color: var(--crumb-active-color);
    }
  }

  /******************************
  DIRECTION
  ******************************/

  &\/trail {
    margin-left: var(--crumb-trail-gap);
    margin-right: var(--crumb-trail-gap);
    color: var(--crumb-trail-color);
  }
}
