/************************************************************
DROPDOWN
************************************************************/

:root {
  --dropdown-body-fill: var(--white);
  --dropdown-body-radius: var(--radius);
  --dropdown-body-shadow: 0px 0px 0px 1px var(--border-color);

  --dropdown-item-padding: .5rem;
  --dropdown-item-color: var(--grey-d1);
  --dropdown-item-hover-color: var(--grey-d2);
  --dropdown-item-hover-fill: var(--grey-l5);
  --dropdown-item-active-fill: var(--grey-l4);
}

.#{$prefix}dropdown {
  display: inline-block;
  position: relative;

  &.is-active {
    .dropdown\/content {
      visibility: visible;
      opacity: 1;
      margin-top: 10px;
    }
    &.dropdown-position {
      &\:top, &\:top-right, &\:top-center {
        .dropdown\/content {
          margin-top: auto;
          margin-bottom: 10px;
        }
      }
    }
  }

  /******************************
  POSITION
  ******************************/

  &-position {
    &\:center {
      .dropdown\/content {
        left: 50%;
        transform: translateX(-50%);
      }
    }
    &\:right {
      .dropdown\/content {
        right: 0;
      }
    }
    &\:top {
      .dropdown\/content {
        top: auto;
        bottom: calc(100% + 0);
        &:before {
          display: none;
        }
      }
      &-center {
        .dropdown\/content {
          top: auto;
          bottom: calc(100% + 0);
          left: 50%;
          transform: translateX(-50%);
          &:before {
            display: none;
          }
        }
      }
      &-right {
        .dropdown\/content {
          top: auto;
          right: 0;
          bottom: calc(100% + 0);
          &:before {
            display: none;
          }
        }
      }
    }
  }

  /******************************
  CHILD ELEMENTS
  ******************************/

  &\/toggle {
    cursor: pointer;
  }
  &\/content {
    visibility: hidden;
    position: absolute;
    top: 100%;
    margin: 0;
    min-width: 12em;
    padding: 0;
    transition: var(--transition);
    opacity: 0;
    z-index: 99;
    &:before {
      display: block;
      content: '';
      position: absolute;
      top: -10px;
      height: 10px;
      width: 100%;
    }
  }
  &\/body {
    background: var(--dropdown-body-fill);
    border-radius: var(--dropdown-body-radius);
    box-shadow: var(--dropdown-body-shadow);
    overflow: hidden;
  }
  &\/item {
    display: block;
    padding: var(--dropdown-item-padding);
    color: var(--dropdown-item-color);
    transition: var(--transition);
    &:hover {
      background: var(--dropdown-item-hover-fill);
      color: var(--dropdown-item-hover-color);
      text-decoration: none;
    }
    &:active {
      background: var(--dropdown-item-active-fill);
    }
  }
}
