/************************************************************
FLAG
************************************************************/

$flag-gutters: 5 !default;

.#{$prefix}flag {

  display: inline-flex;
  vertical-align: middle;
  align-items: center;

  &\/item {

  }

  /******************************
  GUTTER
  ******************************/

	&-gutter {
		@while $flag-gutters > 0 {
      &\:u#{$flag-gutters * 2} {
        .flag\/item {
          margin-right: var(--u#{$flag-gutters * 2});
          &:last-child {
            margin-right: 0;
          }
        }
			}
			$flag-gutters: $flag-gutters - 1;
		}
	}
}
