/************************************************************
LIST
************************************************************/

$list-gutters: 5 !default;

.#{$prefix}list {

  list-style: none;
  margin: 0;
  padding: 0;

  &\/item {
    display: flex;
    align-items: center;
    margin: 0;
    padding: 0;
    text-decoration: none;
    &:hover {
      text-decoration: none;
    }
  }

  /******************************
  GUTTER
  ******************************/

  &-gutter {
    @while $list-gutters > 0 {
      &\:u#{$list-gutters * 2} {
        .list\/item {
          margin-bottom: var(--u#{$list-gutters * 2});
          &:last-child {
            margin-bottom: 0;
          }
        }
      }
      $list-gutters: $list-gutters - 1;
    }
  }

  /******************************
  DIRECTION
  ******************************/

  &\:inline {
    display: flex;
    list-style: none;
    margin: 0;
    padding: 0;

    .list\/item {
      margin-bottom: 0;
    }
    &.list-gutter {
      @while $list-gutters > 0 {
        &\:u#{$list-gutters * 2} {
          .list\/item {
            margin-right: var(--u#{$list-gutters * 2});
            &:last-child {
              margin-right: 0;
            }
          }
        }
        $list-gutters: $list-gutters - 1;
      }
    }
  }
}
