/************************************************************
NOTICE
************************************************************/

.#{$prefix}notice {
  display: none;
  position: relative;
  width: 100%;
  align-items: center;
  background: var(--grey);
  border-radius: var(--radius);
  color: white;
  opacity: 1;
  transition: opacity .2s;
  overflow: hidden;

  &.is-active {
    display: flex;
  }

  /******************************
  CHILD ELEMENTS
  ******************************/

  &\/content {
    padding: var(--u3);
  }
	&\/close {
		display: flex;
		align-items: center;
		justify-content: center;
		position: absolute;
		top: 0;
		right: 0;
    width: 45px;
    height: 45px;
		color: white;
    cursor: pointer;

		span {
			display: block;
			position: relative;
			width: 15px;
			height: 2px;
			background: transparent;

			&:before {
				display: block;
				position: absolute;
				bottom: 0;
				content: '';
				width: 15px;
				height: 2px;
				background: var(--white);
				border-radius: 20px;
				transform: rotate(-45deg);
				transition: bottom 300ms 300ms cubic-bezier(0.23, 1, 0.32, 1), transform 300ms cubic-bezier(0.23, 1, 0.32, 1);
			}
			&:after {
				display: block;
				position: absolute;
				top: 0;
				content: '';
				width: 16px;
				height: 2px;
				background: var(--white);
				border-radius: 20px;
				transform: rotate(45deg);
				transition: top 300ms 300ms cubic-bezier(0.23, 1, 0.32, 1), transform 300ms cubic-bezier(0.23, 1, 0.32, 1);
			}
		}
	}
}
